#include <bits/stdc++.h>

using namespace std;

//Ways to generate subsets of a set.

// Method 1 :

void search(int n)
{
	if(k == n) return;

	else
	{
		search(k+1);
		subset.push_back(k);
		search(k+1);
		subset.pop.back();
	}
}
// abstracting this method, you can think as a Tree generated by each recursion
// in this function.

// Method 2:


for(int b=0; b=(1<<n); ++b)
{
	for(int i=0; i < n; ++i)
		if( b&(1<<i) ) subset.push_back(i);
}

// the code above shows how we can find the elements of a subset that corresponds to a bit sequence.
// pay atentio in the first for loop, goes through the subsets of a set n elements.
